(** This module provides utilities for constructing a dependency graph
      from files generated by [coqdep]. *)

type input =
  | FromDependFile of string
  | FromDotFile of string

type renderer =
   | Graphviz
   | Cytoscape

type graph

val parse_dep : Directory_mappings.t -> in_channel -> graph
(** [parse_dep mappings ch] parses dependencies generated by [coqdep].
      The [mappings] argument is used to handle the physical-to-logical
      path mapping introduced by the [-Q] option of rocqnavi. *)

val parse_dep_file : Directory_mappings.t -> string -> graph
(** Same as [parse_dep], but the dependencies are specified by filename. *)

val to_graphviz : graph -> Graphviz.dot

val to_cytoscape_elements_json : graph -> string
